<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span></li><li><span><a href="#Examining-Data-for-Potential-Issues" data-toc-modified-id="Examining-Data-for-Potential-Issues-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Examining Data for Potential Issues</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Missing Values</a></span><ul class="toc-item"><li><span><a href="#Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values" data-toc-modified-id="Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Show the number of null values only of the columns that actually have null values</a></span></li><li><span><a href="#Remove-the-columns-that-have-more-than-10,000-null-values-in-them" data-toc-modified-id="Remove-the-columns-that-have-more-than-10,000-null-values-in-them-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Remove the columns that have more than 10,000 null values in them</a></span></li><li><span><a href="#Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null." data-toc-modified-id="Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Create a new dataframe that shows only the row where <code>displ</code> is null.</a></span></li><li><span><a href="#Fill-nan-values-with-the-most-appropriate-technique" data-toc-modified-id="Fill-nan-values-with-the-most-appropriate-technique-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Fill nan values with the most appropriate technique</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Incorrect-Values" data-toc-modified-id="Incorrect-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Incorrect Values</a></span><ul class="toc-item"><li><span><a href="#Check-similar-rows" data-toc-modified-id="Check-similar-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Check similar rows</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Low-Variance-Columns" data-toc-modified-id="Low-Variance-Columns-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Low Variance Columns</a></span><ul class="toc-item"><li><span><a href="#Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame." data-toc-modified-id="Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame.-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.</a></span></li></ul></li><li><span><a href="#Extreme-Values-and-Outliers" data-toc-modified-id="Extreme-Values-and-Outliers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extreme Values and Outliers</a></span></li><li><span><a href="#Data-Type-Correction" data-toc-modified-id="Data-Type-Correction-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Type Correction</a></span><ul class="toc-item"><li><span><a href="#Check-the-data-type-of-each-column" data-toc-modified-id="Check-the-data-type-of-each-column-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Check the data type of each column</a></span></li><li><span><a href="#Cleaning-years" data-toc-modified-id="Cleaning-years-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cleaning years</a></span></li></ul></li><li><span><a href="#Cleaning-Text-and-Removing-Special-Characters" data-toc-modified-id="Cleaning-Text-and-Removing-Special-Characters-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Cleaning Text and Removing Special Characters</a></span></li><li><span><a href="#Finding-and-Removing-Duplicates" data-toc-modified-id="Finding-and-Removing-Duplicates-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Finding and Removing Duplicates</a></span><ul class="toc-item"><li><span><a href="#Drop-duplicate-rows-that-are-completely-equal" data-toc-modified-id="Drop-duplicate-rows-that-are-completely-equal-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Drop duplicate rows that are completely equal</a></span></li><li><span><a href="#Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns." data-toc-modified-id="Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns.-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.</a></span></li></ul></li><li><span><a href="#Export-clean-dataset" data-toc-modified-id="Export-clean-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Export clean dataset</a></span></li></ul></div>

# Data Cleaning


Lab Goals

+ Examine data for potential issues.
+ Identify and fill in missing values.
+ Identify and correct incorrect values.
+ Remove low variance columns.
+ Identify potential outliers.
+ Correct incorrect data types.
+ Remove special characters and clean categorical variables.
+ Identify and remove duplicate records.

Introduction

When working with data sets, you will find that they often require a bit of cleaning. Whether Pandas originally read the data types incorrectly, records are duplicated, the data contains special characters or missing value, or there are slightly different references to the same entity, every data analyst must know how to clean the data they are working with before analyzing it. In this lesson, you will learn about some of the most common problems that make data messy and methods for correcting those problems and cleaning your data.

The data set we are going to be using for this lesson is a messy version of the vehicles data set we worked with in the previous lesson. Let's import this version of our data set so that we can then practice cleaning it up.

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [3]:
#Load data from vehicles_messy.csv

data = pd.read_csv('../data/vehicles_messy.csv')

In [4]:
data.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [42]:
data.drop_duplicates().shape == data.shape

True

# Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any **potential issues**. Some of the things we are interested in identifying in the data at this stage include:

- Missing values
- Special characters
- Incorrect values
- Extreme values or outliers
- Duplicate records
- Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand. We can start by visually inspecting the data using the `.head` method, which will show us the first 5 rows of data.

But how big actually is our dataframe??? Check it with `.shape` method

In [44]:
data.shape

(37843, 70)

Let's dive a little more in the content of our data set. Is there any method that shows us the **column names**, its **data types** and number of **non-null values**?

In [45]:
data.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'feScore', 'fuelCost08', 'fuelCostA08',
       'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA', 'highway08',
       'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE',
       'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make', 'model',
       'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'charge240b',
       'createdOn', 'modifiedOn', 'phevCity', 'phevHwy', 'phevComb'],
      dtype='object')

In [46]:
data.dtypes

barrels08     float64
barrelsA08    float64
charge120     float64
charge240     float64
city08          int64
               ...
createdOn      object
modifiedOn     object
phevCity        int64
phevHwy         int64
phevComb        int64
Length: 70, dtype: object

In [47]:
data.isna().sum()

barrels08     0
barrelsA08    0
charge120     0
charge240     0
city08        0
             ..
createdOn     0
modifiedOn    0
phevCity      0
phevHwy       0
phevComb      0
Length: 70, dtype: int64

# Missing Values

From this initial view, we can see that our data set contains some columns that have missing values in them and others that seem to have a lot of zero values. 

Let's see how prevalent missing values are in our data. We can use the Pandas `.isnull()` method to check whether the value in each field is missing (*null*) and return either True or False for each field. 

We can use the `.sum()` method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

## Show the number of null values only of the columns that actually have null values

In [5]:
data['startStop'].isnull().sum()

31705

We can see that some columns have relatively few null values while others have tens of thousands of nulls. For fields that have a lot of null values, you will often have to make a judgement call. If you don't think the information is going to be very useful to your analysis, then you would remove those columns from your data frame.

## Remove the columns that have more than 10,000 null values in them

In Pandas, we can do that using the drop method. For our purposes, let's remove the columns that have more than 10,000 null values in them. We will add these column names to a list, and then we will pass those columns to the drop method and indicate that we want columns (not rows) dropped by setting the axis parameter to 1.

In [6]:
nan_cols = data.isna().sum()>10000 
data.drop(columns = nan_cols[nan_cols].index, inplace=True)

This leaves us with just a handful of remaining columns that have null values. Of the columns that remain, it looks like the cylinders column and the displ column have a similar number of nulls. Perhaps they are missing for similar reasons. We can investigate this by subsetting the data set and looking at just the records where displ is null and just the columns we think will be informative in allowing us to determine a reason.

## Create a new dataframe that shows only the row where `displ` is null. 
Keep only the columns you think are useful

In [7]:
data2 = data[data['displ'].isnull()]
data2

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.240,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,85,0.0000,0,0.0,40.0000,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0000,0,0.0,0.0,37.0000,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.312,0.0,0.0,0.0,74,0.0000,0,0.0,0.0,46.0000,0.0,0,-1,0.0,0.0,65,0.0000,0,0.0,52.0000,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0000,0,0.0,0.0,59.0000,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.522,0.0,0.0,0.0,45,0.0000,0,0.0,0.0,75.0000,0.0,0,-1,0.0,0.0,39,0.0000,0,0.0,87.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0000,0,0.0,0.0,102.0000,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30969,0.192,0.0,0.0,4.0,120,119.6000,0,0.0,0.0,28.1744,0.0,0,-1,0.0,0.0,105,105.3754,0,0.0,31.9856,0.0,0.0,NaN,NaN,Front-Wheel Drive,37,10,600,0,Electricity,Electricity,10,-1,92,92.0000,0,0.0,0.0,36.6438,0.0,0,0,38168,0,19,Kia,Soul Electric,N,False,0,97,93,148.0,0.0,113.8,0.0,Automatic (A1),170.9000,0.0,131.4000,0.0,Small Station Wagons,2017,3750,0.00,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30972,0.204,0.0,0.0,10.0,98,97.5636,0,0.0,0.0,35.0000,0.0,0,-1,0.0,0.0,99,99.0945,0,0.0,34.0000,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0000,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5,0.0,214.8,0.0,Automatic (A1),132.2000,0.0,136.9000,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.192,0.0,0.0,12.0,101,101.4750,0,0.0,0.0,33.0000,0.0,0,-1,0.0,0.0,104,103.7678,0,0.0,32.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,21,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0000,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1,0.0,226.9,0.0,Automatic (A1),137.5000,0.0,144.6000,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.210,0.0,0.0,12.0,92,92.4713,0,0.0,0.0,36.0000,0.0,0,-1,0.0,0.0,98,97.5232,0,0.0,35.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,15,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0000,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9,0.0,346.9,0.0,Automatic (A1),125.3000,0.0,141.6000,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.216,0.0,0.0,12.0,91,91.2362,0,0.0,0.0,37.0000,0.0,0,-1,0.0,0.0,93,92.5663,0,0.0,36.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,12,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0000,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5,0.0,203.2,0.0,Automatic (A1),124.3000,0.0,128.4000,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

## Fill nan values with the most appropriate technique 
*HINT: Electric cars do not have cylinders and can therefore not have any displacement*

In [8]:
data2[['cylinders', 'displ']].fillna(0, inplace = True)

data2

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.240,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,85,0.0000,0,0.0,40.0000,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0000,0,0.0,0.0,37.0000,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.312,0.0,0.0,0.0,74,0.0000,0,0.0,0.0,46.0000,0.0,0,-1,0.0,0.0,65,0.0000,0,0.0,52.0000,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0000,0,0.0,0.0,59.0000,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.522,0.0,0.0,0.0,45,0.0000,0,0.0,0.0,75.0000,0.0,0,-1,0.0,0.0,39,0.0000,0,0.0,87.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0000,0,0.0,0.0,102.0000,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30969,0.192,0.0,0.0,4.0,120,119.6000,0,0.0,0.0,28.1744,0.0,0,-1,0.0,0.0,105,105.3754,0,0.0,31.9856,0.0,0.0,NaN,NaN,Front-Wheel Drive,37,10,600,0,Electricity,Electricity,10,-1,92,92.0000,0,0.0,0.0,36.6438,0.0,0,0,38168,0,19,Kia,Soul Electric,N,False,0,97,93,148.0,0.0,113.8,0.0,Automatic (A1),170.9000,0.0,131.4000,0.0,Small Station Wagons,2017,3750,0.00,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30972,0.204,0.0,0.0,10.0,98,97.5636,0,0.0,0.0,35.0000,0.0,0,-1,0.0,0.0,99,99.0945,0,0.0,34.0000,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0000,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5,0.0,214.8,0.0,Automatic (A1),132.2000,0.0,136.9000,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.192,0.0,0.0,12.0,101,101.4750,0,0.0,0.0,33.0000,0.0,0,-1,0.0,0.0,104,103.7678,0,0.0,32.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,21,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0000,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1,0.0,226.9,0.0,Automatic (A1),137.5000,0.0,144.6000,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.210,0.0,0.0,12.0,92,92.4713,0,0.0,0.0,36.0000,0.0,0,-1,0.0,0.0,98,97.5232,0,0.0,35.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,15,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0000,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9,0.0,346.9,0.0,Automatic (A1),125.3000,0.0,141.6000,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.216,0.0,0.0,12.0,91,91.2362,0,0.0,0.0,37.0000,0.0,0,-1,0.0,0.0,93,92.5663,0,0.0,36.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,12,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0000,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5,0.0,203.2,0.0,Automatic (A1),124.3000,0.0,128.4000,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

## Bonus: 
Now that we have filled in those null values, there are only two columns in the data set that still have null values: trany and drive. Use what you have learned in this section to investigate and potentially fill in the remaining null values.

In [9]:
data2['trany'].isna().sum()

9

# Incorrect Values

In addition to null values, we also want to try to identify any values that seem incorrect. For example, in the previous section, we learned that a vehicle without cylinders should not have displacement and vice versa. Let's check to see if there are any cases that violate these rules.

In [10]:
mask = (data2['fuelType'] == 'Electricity') & (data2['fuelType1'] == 'Electricity')
cols_to_replace = ['barrels08', 'city08', 'highwayA08', 'comb08' ] 
data2.loc[mask, cols_to_replace] = 0

data2

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.0,0.0,0.0,0.0,0,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,0,0.0000,0,0.0,40.0000,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0000,0,0.0,0.0,37.0000,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.0,0.0,0.0,0.0,0,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,0,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.0,0.0,0.0,0.0,0,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,0,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.0,0.0,0.0,0.0,0,0.0000,0,0.0,0.0,46.0000,0.0,0,-1,0.0,0.0,0,0.0000,0,0.0,52.0000,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0000,0,0.0,0.0,59.0000,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.0,0.0,0.0,0.0,0,0.0000,0,0.0,0.0,75.0000,0.0,0,-1,0.0,0.0,0,0.0000,0,0.0,87.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0000,0,0.0,0.0,102.0000,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30969,0.0,0.0,0.0,4.0,0,119.6000,0,0.0,0.0,28.1744,0.0,0,-1,0.0,0.0,0,105.3754,0,0.0,31.9856,0.0,0.0,NaN,NaN,Front-Wheel Drive,37,10,600,0,Electricity,Electricity,10,-1,92,92.0000,0,0.0,0.0,36.6438,0.0,0,0,38168,0,19,Kia,Soul Electric,N,False,0,97,93,148.0,0.0,113.8,0.0,Automatic (A1),170.9000,0.0,131.4000,0.0,Small Station Wagons,2017,3750,0.00,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30972,0.0,0.0,0.0,10.0,0,97.5636,0,0.0,0.0,35.0000,0.0,0,-1,0.0,0.0,0,99.0945,0,0.0,34.0000,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0000,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5,0.0,214.8,0.0,Automatic (A1),132.2000,0.0,136.9000,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.0,0.0,0.0,12.0,0,101.4750,0,0.0,0.0,33.0000,0.0,0,-1,0.0,0.0,0,103.7678,0,0.0,32.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,21,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0000,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1,0.0,226.9,0.0,Automatic (A1),137.5000,0.0,144.6000,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.0,0.0,0.0,12.0,0,92.4713,0,0.0,0.0,36.0000,0.0,0,-1,0.0,0.0,0,97.5232,0,0.0,35.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,15,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0000,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9,0.0,346.9,0.0,Automatic (A1),125.3000,0.0,141.6000,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.0,0.0,0.0,12.0,0,91.2362,0,0.0,0.0,37.0000,0.0,0,-1,0.0,0.0,0,92.5663,0,0.0,36.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,12,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0000,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5,0.0,203.2,0.0,Automatic (A1),124.3000,0.0,128.4000,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

Is there any row that seems to have strange values?

Here we have identified a vehicle with a regular gasoline engine that reportedly does not have any cylinders but does have a value for displacement.

The way we would correct this would be to either perform some domain research or ask a domain expert to find out how many actual cylinders this vehicle had. Alternatively, you can also try to look at similar vehicles in the data set and determine the most likely value for this field.

## Check similar rows

In [12]:
duplicated_partial = data2.drop_duplicates(subset = 'model')

data2 = duplicated_partial

data2 = data2.loc[data2['fuelType'] == 'Electricity']

data2.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,40.0,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0,0,0.0,0.0,37.0,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,47.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0,0,0.0,0.0,53.0,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,46.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,52.0,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0,0,0.0,0.0,59.0,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,75.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,87.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0,0,0.0,0.0,102.0,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8147,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,40.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,45.0,0.0,0.0,NaN,NaN,NaN,0,-1,900,0,Electricity,Electricity,-1,-1,66,0.0,0,0.0,0.0,51.0,0.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,False,0,0,33,0.0,0.0,0.0,0.0,NaN,120.3571,0.0,93.6111,0.0,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0

In [14]:
data2['trany'] = "Automatic"

data2.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,40.0,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0,0,0.0,0.0,37.0,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,Automatic,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,47.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0,0,0.0,0.0,53.0,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,Automatic,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,46.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,52.0,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0,0,0.0,0.0,59.0,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,Automatic,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,75.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,87.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0,0,0.0,0.0,102.0,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,Automatic,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8147,0.0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,40.0,0.0,0,-1,0.0,0.0,0,0.0,0,0.0,45.0,0.0,0.0,NaN,NaN,NaN,0,-1,900,0,Electricity,Electricity,-1,-1,66,0.0,0,0.0,0.0,51.0,0.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,False,0,0,33,0.0,0.0,0.0,0.0,Automatic,120.3571,0.0,93.6111,0.0,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0

Suppose that using one of the aforementioned methods, we found out that this vehicle actually has a 4 cylinder engine. Update that specific value in the data frame.

# Low Variance Columns

When analyzing data, we want the fields we are working with to be informative, and we will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

Let's try to identify columns where at least 90% of the values are the same so that we can remove them from our data set. To do this, we are going to create an empty list called low_variance that will eventually contain the names of columns that fit our criteria.

We will then write a for loop that will take the minimum and the 90th percentile value for all the numeric columns in our data set (identified via the _get_numeric_data method). If the 90th percentile and the minimum are equal to each other, that means that at least 90% of the values in that column are the same and we will append that column name to our low_variance list.

In [15]:
data2 = data2.loc[:, (data2 != 0).any(axis=0)]
   
data2.head()

,charge240,city08U,cityE,co2A,comb08U,combE,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv2,pv4,range,rangeCity,rangeHwy,trany,UCity,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.0,0.0,41.0,-1,0.0,40.0,NaN,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,0,0,90,0.0,0.0,Automatic,116.2069,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.0,0.0,41.0,-1,0.0,47.0,NaN,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,0,0,Toyota,RAV4 EV,N,0,0,88,0.0,0.0,Automatic,116.2069,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.0,0.0,46.0,-1,0.0,52.0,NaN,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,0,0,29,0.0,0.0,Automatic,105.3125,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.0,0.0,75.0,-1,0.0,87.0,NaN,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,0,0,38,0.0,0.0,Automatic,62.4074,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8147,0.0,0.0,40.0,-1,0.0,45.0,NaN,NaN,NaN,0,-1,900,Electricity,Electricity,-1,-1,66,0.0,51.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,0,0,33,0.0,0.0,Automatic,120.3571,93.6111,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

This returned 34 columns that we could potentially eliminate due to not having high enough variability to be informative. Of course, before we do this, we should check the values that do exist in these fields to confirm that they are not very informative. Once they have been checked, we can use the the drop method like we did earlier in this lesson to remove those columns from our data frame.

In [17]:
data2.sort_values(by = ['range'], ascending = False).head()

,charge240,city08U,cityE,co2A,comb08U,combE,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv2,pv4,range,rangeCity,rangeHwy,trany,UCity,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
30974,12.0,92.4713,36.0,-1,97.5232,35.0,NaN,NaN,All-Wheel Drive,15,10,700,Electricity,Electricity,10,-1,105,104.5008,32.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,0,0,315,305.90,346.90,Automatic,125.3,141.6,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016
28592,12.0,95.3056,35.0,-1,99.8433,34.0,NaN,NaN,All-Wheel Drive,5,10,650,Electricity,Electricity,10,-1,106,106.0124,32.0,26,94,36009,0,0,Tesla,Model S AWD - 85D,N,0,0,270,257.10,285.30,Automatic,126.4,140.6,Large Cars,2015,3500,4.75,Thu Jan 22 00:00:00 EST 2015,Wed Aug 12 00:00:00 EDT 2015
29443,12.0,95.3056,35.0,-1,99.8433,34.0,NaN,NaN,All-Wheel Drive,7,10,650,Electricity,Electricity,10,-1,106,106.0124,32.0,26,94,36786,0,0,Tesla,Model S AWD - 90D,N,0,0,270,257.10,285.30,Automatic,126.4,140.6,Large Cars,2015,3500,4.75,Thu Aug 06 00:00:00 EDT 2015,Wed Aug 12 00:00:00 EDT 2015
29935,12.0,87.8784,38.0,-1,88.8876,38.0,NaN,NaN,Rear-Wheel Drive,71,10,750,Electricity,Electricity,10,-1,90,90.1072,37.0,26,94,37235,0,0,Tesla,Model S (90 kW-hr battery pack),N,0,0,265,262.70,266.80,Automatic,110.4,113.2,Large Cars,2016,3000,4.75,Thu Jan 21 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016
24784,12.0,87.9000,38.0,-1,88.8000,38.0,NaN,NaN,Rear-Wheel Drive,1,-1,750,Electricity,Electricity,-1,-1,90,90.1000,37.0,26,94,32557,0,0,Tesla,Model S,Y,0,0,265,262.69,266.78,Automatic,110.4,113.2,Large Cars,2012,3000,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014

## Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.

In [25]:
data2.drop(columns = ['lv2', 'lv4']).head()

,charge240,city08U,cityE,co2A,comb08U,combE,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,make,model,mpgData,range,rangeCity,rangeHwy,trany,UCity,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.0,0.0,41.0,-1,0.0,40.0,NaN,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,Nissan,Altra EV,N,90,0.0,0.0,Automatic,116.2069,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.0,0.0,41.0,-1,0.0,47.0,NaN,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,Toyota,RAV4 EV,N,88,0.0,0.0,Automatic,116.2069,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.0,0.0,46.0,-1,0.0,52.0,NaN,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,Ford,Th!nk,N,29,0.0,0.0,Automatic,105.3125,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.0,0.0,75.0,-1,0.0,87.0,NaN,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,Ford,Explorer USPS Electric,N,38,0.0,0.0,Automatic,62.4074,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8147,0.0,0.0,40.0,-1,0.0,45.0,NaN,NaN,NaN,0,-1,900,Electricity,Electricity,-1,-1,66,0.0,51.0,0,0,17331,Nissan,Hyper-Mini,N,33,0.0,0.0,Automatic,120.3571,93.6111,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

# Extreme Values and Outliers

Now that we have removed low variance columns, we should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

A common method for identifying outliers is one that leverages the interquartile range (IQR). Once the IQR is calculated, it is multiplied by a constant (typically 1.5) and lower and upper bounds are established at:

    25th Percentile - (IQR x 1.5)
    75th Percentile + (IQR x 1.5)

Any values outside this range are potential outliers and should be investigated.

Let's look at how we would do this for our data set using Python. We will use the Pandas describe function to easily calculate the 25th and 75th percentiles for every column and transpose the results so that we can easily reference the values in calculating the interquartile ranges.

In [26]:
stats = data2.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

,count,mean,std,min,25%,50%,75%,max,IQR
charge240,56.0,6.500000,4.535717,0.0000,3.8750,6.00000,12.00000,12.0000,8.12500
city08U,56.0,74.392180,48.869725,0.0000,0.0000,89.37140,107.56175,138.3040,107.56175
cityE,56.0,39.543343,14.532249,24.0000,31.7500,36.50000,40.25000,90.0000,8.50000
co2A,56.0,-1.000000,0.000000,-1.0000,-1.0000,-1.00000,-1.00000,-1.0000,0.00000
comb08U,56.0,71.970786,46.006734,0.0000,0.0000,92.32515,104.01535,124.3601,104.01535
combE,56.0,40.857368,15.499511,27.0000,32.0000,36.00000,40.05655,96.0000,8.05655
cylinders,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
displ,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
engId,56.0,126.357143,250.839132,0.0000,1.0000,7.50000,100.00000,902.0000,99.00000
feScore,56.0,5.482143,5.460573,-1.0000,-1.0000,10.00000,10.00000,10.0000,11.00000
fuelCost08,56.0,796.428571,300.735030,550.0000,600.0000,700.00000,800.00000,1850.0000,200.00000
ghgScore,56.0,5.482143,5.460573,-1.0000,-1.0000,10.00000,10.00000,10.0000,11.00000
ghgScoreA,56.0,-1.000000,0.000000,-1.0000,-1.0000,-1.00000,-1.00000,-1.0000,0.00000
highway08,56.0,87.196429,20.754338,33.0000,79.0000,94.00000,101.25000,111.0000,22.25000
highway08U,56.0,69.809134,43.954170,0.0000,0.0000,93.47000,101.41500,111.3700,101.41500
highwayE,56.0,42.453475,17.181535,30.0000,33.2124,36.00000,43.00000,103.0000,9.78760
hlv,56.0,11.535714,12.408156,0.0000,0.0000,2.00000,26.00000,26.0000,26.00000
hpv,56.0,45.875000,46.437862,0.0000,0.0000,36.50000,94.00000,94.0000,94.00000
id,56.0,32896.321429,5607.417876,16423.0000,31064.7500,33389.50000,36979.25000,38173.0000,5914.50000
lv2,56.0,0.107143,0.801784,0.0000,0.0000,0.00000,0.00000,6.0000,0.00000
lv4,56.0,2.750000,6.520597,0.0000,0.0000,0.00000,0.00000,22.0000,0.00000
range,56.0,134.892857,86.889832,29.0000,70.0000,88.00000,238.50000,315.0000,168.50000
rangeCity,56.0,117.621057,101.699997,0.0000,0.0000,89.40500,233.77500,305.9000,233.77500
rangeHwy,56.0,117.680020,108.995018,0.0000,0.0000,78.34000,243.25000,346.9000,243.25000
UCity,56.0,130.193566,37.062923,50.2985,110.4000,123.60000,153.65685,197.5771,43.25685
UHighway,56.0,120.937314,28.662869,46.1644,112.9060,130.65000,141.10000,159.1000,28.19400
year,56.0,2011.214286,5.990035,1998.0000,2011.0000,2013.00000,2016.00000,2017.0000,5.00000
youSaveSpend,56.0,2767.857143,1503.675151,-2500.0000,2750.0000,3250.00000,3750.00000,4000.0000,1000.00000
charge240b,56.0,1.607143,2.204261,0.0000,0.0000,0.00000,4.75000,5.0000,4.75000

We will then create an empty data frame called outliers with the same columns as our data set. Finally, we will loop through each column in the data calculating the lower and upper bounds, retrieving records where the value for that column falls outside the bounds we established, and appending those results to our outlier data frame.

In [27]:
data2.shape

(56, 39)

In [28]:
outliers = pd.DataFrame(columns=data2.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data2[(data2[col] < lower) | 
                   (data2[col] > upper)].copy()
    results['Outlier'] = col
    outliers = pd.concat([outliers, results])
    

outliers.head()

,charge240,city08U,cityE,co2A,comb08U,combE,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,range,rangeCity,rangeHwy,trany,UCity,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,Outlier
8146,0.0,0.0,75.0,-1,0.0,87.0,NaN,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,38,0.0,0.0,Automatic,62.4074,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,cityE
23026,0.0,0.0,54.0,-1,0.0,58.0,NaN,NaN,2-Wheel Drive,0,-1,1150,Electricity,Electricity,-1,-1,54,0.0,63.0,0,0,30965,0,0,Ford,Ranger Pickup 2WD,N,50,0.0,0.0,Automatic,88.6842,76.5909,Standard Pickup Trucks 2WD,2001,1000,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,cityE
23032,0.0,0.0,69.0,-1,0.0,71.0,NaN,NaN,NaN,0,-1,1400,Electricity,Electricity,-1,-1,46,0.0,73.0,0,0,30970,0,0,Honda,EV Plus,N,81,0.0,0.0,Automatic,68.7755,66.0784,Compact Cars,1999,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,cityE
23035,0.0,0.0,90.0,-1,0.0,96.0,NaN,NaN,2-Wheel Drive,0,-1,1850,Electricity,Electricity,-1,-1,33,0.0,103.0,0,0,30973,0,0,Dodge,Caravan/Grand Caravan 2WD,N,70,0.0,0.0,Automatic,50.2985,46.1644,Minivan - 2WD,1999,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,cityE
23036,0.0,0.0,90.0,-1,0.0,96.0,NaN,NaN,Front-Wheel Drive,0,-1,1850,Electricity,Electricity,-1,-1,33,0.0,103.0,0,0,30974,0,0,Plymouth,Voyager/Grand Voyager 2WD,N,70,0.0,0.0,Automatic,50.2985,46.1644,Minivan - 2WD,1999,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,cityE

Our outliers data frame should now be populated with records that you can investigate further and determine whether they should be kept in the data or dropped. The Outlier column we added before appending the results for the column to the outliers data frame will let you know what column in each record contained the outlier. If you find that this method is returning too many results, you can be more stringent with your cutoff criteria (e.g. increasing the constant by which you multiply the IQR to 3 instead of 1.5).

# Data Type Correction

One common problem that is often overlooked is incorrect data types. This typically occurs when there is a numeric variable that should actually be represented as a categorical variable.

## Check the data type of each column

In [32]:
data2.dtypes

charge240       float64
city08U         float64
cityE           float64
co2A              int64
comb08U         float64
combE           float64
cylinders       float64
displ           float64
drive            object
engId             int64
feScore           int64
fuelCost08        int64
fuelType         object
fuelType1        object
ghgScore          int64
ghgScoreA         int64
highway08         int64
highway08U      float64
highwayE        float64
hlv               int64
hpv               int64
id                int64
lv2               int64
lv4               int64
make             object
model            object
mpgData          object
range             int64
rangeCity       float64
rangeHwy        float64
trany            object
UCity           float64
UHighway        float64
VClass           object
year              int64
youSaveSpend      int64
charge240b      float64
createdOn        object
modifiedOn       object
dtype: object

## Cleaning years
Do you think column year is a continuous variable? Would you change it onto another dtype?

In [ ]:
# La columna 'year' no es una variable continua, sino una columna discreta.

You can apply this technique to any column whose data type you would like to change.

In [ ]:
# Puedes modificar el tipo de dato de las columnas utilizando .astype()

# Cleaning Text and Removing Special Characters

The presence of special characters in our fields has the potential to make analyzing our data challenging. Imagine not being able to perform calculations on a numeric field because it was currently represented as an object data type due to the fact that it had a dollar sign ($) in it. 

Similarly, imagine having a categorical field where you could not group records that belong in the same group together because in one field you are grouping by, terms that refer to the same thing are sometimes hyphenated. In cases like this, it is necessary to remove special characters so that we can properly analyze the data.

In our vehicles data set, the trany field has several special characters (parentheses, hyphens, etc.). Check the unique values and clean the column.

hint: check the `replace` function

In [37]:
data2['trany'] = data2['trany'].str.replace(r'[()]', '', regex=True) 
data2['trany'] = data2['trany'].str.replace('-', '', regex=False)
data2['trany']

7138     Automatic
7139     Automatic
8144     Automatic
8146     Automatic
8147     Automatic
23026    Automatic
23029    Automatic
23032    Automatic
23035    Automatic
23036    Automatic
23038    Automatic
23040    Automatic
23041    Automatic
23137    Automatic
23138    Automatic
23807    Automatic
24051    Automatic
24052    Automatic
24472    Automatic
24473    Automatic
24474    Automatic
24784    Automatic
25570    Automatic
25615    Automatic
25617    Automatic
25683    Automatic
25684    Automatic
25701    Automatic
25715    Automatic
25955    Automatic
25986    Automatic
27704    Automatic
27747    Automatic
28141    Automatic
28414    Automatic
28575    Automatic
28591    Automatic
28592    Automatic
28720    Automatic
29443    Automatic
29444    Automatic
29652    Automatic
29654    Automatic
29672    Automatic
29750    Automatic
29751    Automatic
29933    Automatic
29935    Automatic
30141    Automatic
30142    Automatic
30143    Automatic
30784    Automatic
30785    Automatic
30973    Automatic
30974    Automatic
30975    Automatic
Name: trany, dtype: object

As you can see, we now have no special characters, consistent naming, and proper spacing. We started out with 47 unique values in this column, and using this technique, we were able to reduce the number of unique values to 39.



# Finding and Removing Duplicates

The final topic we are going to cover in this lab is how to identify and remove duplicate rows (or rows that refer to the same entity) in our data. When trying to identify duplicates, we will use the columns (or attributes) of the data to help us determine what entities are similar enough to be considered the same entity. We want to start with all the columns we currently have available to us and work our way toward a lesser number of attributes in an intuitive fashion. In this process, the act of dropping duplicated records is easy, but identifying the correct attributes for comparison and which records to drop is sometimes quite challenging.

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. 

Pandas provides us with the ability to do that via the `drop_duplicates method`.

## Drop duplicate rows that are completely equal

In [35]:
data2.drop_duplicates().head()

,charge240,city08U,cityE,co2A,comb08U,combE,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,range,rangeCity,rangeHwy,trany,UCity,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.0,0.0,41.0,-1,0.0,40.0,NaN,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,90,0.0,0.0,Automatic,116.2069,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.0,0.0,41.0,-1,0.0,47.0,NaN,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,0,0,Toyota,RAV4 EV,N,88,0.0,0.0,Automatic,116.2069,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.0,0.0,46.0,-1,0.0,52.0,NaN,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,29,0.0,0.0,Automatic,105.3125,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.0,0.0,75.0,-1,0.0,87.0,NaN,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,38,0.0,0.0,Automatic,62.4074,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8147,0.0,0.0,40.0,-1,0.0,45.0,NaN,NaN,NaN,0,-1,900,Electricity,Electricity,-1,-1,66,0.0,51.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,33,0.0,0.0,Automatic,120.3571,93.6111,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

This tells us that there were no records that matched exactly across all columns. However, if we reduce the number of columns in our data that we are interested in, we can try again and have a higher likelihood of finding duplicate records.

## Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.

In [39]:
columns_to_keep = [
    "charge240", "city08U", "cityE", "co2A", "comb08U", "combE", "cylinders", "displ",
    "drive", "engId", "feScore", "fuelCost08", "fuelType", "fuelType1", "ghgScore", "ghgScoreA",
    "highway08", "highway08U", "highwayE", "hlv", "hpv", "id", "lv2", "lv4", "make", "model",
    "mpgData", "range", "rangeCity", "rangeHwy", "trany", "UCity", "UHighway", "VClass", "year",
    "youSaveSpend", "charge240b", "createdOn", "modifiedOn"]

data2_subset = data2[columns_to_keep]
data2_cleaned = data2_subset.drop_duplicates()

With the reduced number of columns, we were able to identify and drop 885 duplicate records.

# Export clean dataset
Export your bright new clean dataset into a csv file and store it in data folder.

In [40]:
data2.to_csv('cleaned_vehicles.csv', index=False)